# Generated by Django 4.1.7 on 2023-04-05 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('feedback', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kitchen_img', models.ImageField(blank=True, null=True, upload_to='hostel_image/')),
                ('recep_img', models.ImageField(blank=True, null=True, upload_to='hostel_image/')),
                ('front_images', models.ImageField(blank=True, null=True, upload_to='hostel_image/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField(default='Address')),
                ('contact', models.CharField(default='977+', max_length=100)),
                ('email', models.EmailField(default='hostel_name@email.com', max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=3, max_digits=4)),
                ('num_rating', models.PositiveIntegerField(default=0)),
                ('wifi_choice', models.CharField(choices=[('5G network', '5G network'), ('Not Available', 'Not Available')], default='5G network', max_length=100)),
                ('canteen_choice', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=100)),
                ('parking_choice', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=100)),
                ('hotwater_choice', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='Deluxe', max_length=100)),
                ('occupancy', models.CharField(choices=[('SINGLE', 'SINGLE'), ('DOUBLE', 'DOUBLE')], default='SINGLE', max_length=50)),
                ('room_type', models.CharField(choices=[('A/C(Air Conditioned)', 'A/C(Air Conditioned)'), ('Non A/C(Non Air Conditioned)', 'Non A/C(Non Air Conditioned)')], default='Non A/C(Non Air Conditioned)', max_length=50)),
                ('maximum', models.PositiveIntegerField(default=10)),
                ('available', models.PositiveIntegerField(default=10)),
                ('cost', models.PositiveIntegerField(default=10000)),
                ('front_img', models.ImageField(blank=True, null=True, upload_to='hostel_image/')),
                ('back_img', models.ImageField(blank=True, null=True, upload_to='hostel_image/')),
                ('side_images', models.ImageField(blank=True, null=True, upload_to='hostel_image/')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('num_rooms', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('user_rating', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.room')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.transaction')),
            ],
        ),
    ]
