# Generated by Django 4.1.7 on 2023-04-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='front_images',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='kitchen_img',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='recep_img',
        ),
    ]
