# Generated by Django 4.1.7 on 2023-03-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
