# Generated by Django 4.1.7 on 2023-04-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_front_images_hostel_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='images',
            new_name='images1',
        ),
        migrations.AddField(
            model_name='hostel',
            name='images2',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_image/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='images3',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_image/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='images4',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_image/'),
        ),
    ]
