# Generated by Django 4.1.7 on 2023-04-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_images_hostel_images1_hostel_images2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='images1',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_image/img1/'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='images2',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_image/img2/'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='images3',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_image/img3/'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='images4',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_image/img4/'),
        ),
    ]
