# Generated by Django 4.1.7 on 2023-04-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_hostel_images1_alter_hostel_images2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='images1',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='images2',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='images3',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='images4',
        ),
    ]
