# Generated by Django 4.1.7 on 2023-04-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_hostel_contact_alter_hostel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='images2',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_image/img2/'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
