# Generated by Django 4.1.7 on 2023-04-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_hostel_images2_alter_hostel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='images3',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_image/img3/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='images4',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_image/img4/'),
        ),
    ]
