# Generated by Django 4.1.7 on 2023-04-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_hostel_images3_hostel_images4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='back_img',
        ),
        migrations.RemoveField(
            model_name='room',
            name='front_img',
        ),
        migrations.RemoveField(
            model_name='room',
            name='side_images',
        ),
        migrations.AddField(
            model_name='room',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='room_image/img1'),
        ),
        migrations.AddField(
            model_name='room',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='room_image/img2'),
        ),
        migrations.AddField(
            model_name='room',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='room_image/img3'),
        ),
    ]
